import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#162027',
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 18,
    paddingVertical: 16,
    justifyContent: 'center',
    gap: 12,
  },
  authLayout: {
    flex: 1,
  },
  authScroll: {
    flex: 1,
  },
  authScrollContent: {
    paddingBottom: 24,
  },
  scrollContentKeyboard: {
    justifyContent: 'flex-start',
    paddingBottom: 96,
  },
  mobileContent: {
    flex: 1,
  },
  mobileShell: {
    flexGrow: 1,
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 96,
    gap: 14,
  },
  mobileTopBar: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  topBarSide: {
    width: 40,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  topIconButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#24303a',
    borderWidth: 1,
    borderColor: '#3d4e5b',
    alignItems: 'center',
    justifyContent: 'center',
  },
  topIconGlyph: {
    color: '#f8f1e6',
    fontSize: 18,
    fontWeight: '800',
  },
  topIconPlaceholder: {
    width: 40,
    height: 40,
  },
  mobileHeaderCopy: {
    flex: 1,
    gap: 2,
    paddingTop: 2,
    minWidth: 0,
    alignItems: 'center',
  },
  mobileCard: {
    backgroundColor: 'rgba(38, 50, 61, 0.82)',
    borderRadius: 22,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: 'rgba(126, 145, 160, 0.22)',
    shadowColor: '#000000',
    shadowOpacity: 0.18,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
  },
  mobileTitle: {
    color: '#f8f1e6',
    fontSize: 27,
    fontWeight: '800',
    lineHeight: 31,
    textAlign: 'center',
  },
  mobilePoweredBy: {
    color: '#93a982',
    fontSize: 10,
    letterSpacing: 1.8,
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  mobileBrand: {
    color: '#d7c6af',
    fontSize: 17,
    fontWeight: '700',
    textAlign: 'center',
  },
  mobileSubtitle: {
    marginTop: 6,
    color: '#c8b9a7',
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
  },
  mobileScreenTitle: {
    color: '#f8f1e6',
    fontSize: 20,
    fontWeight: '800',
    lineHeight: 24,
    textAlign: 'center',
  },
  mobileScreenSubtitle: {
    marginTop: 4,
    color: '#b9af9f',
    fontSize: 12,
    lineHeight: 16,
    textAlign: 'center',
  },
  homeWelcomeTitle: {
    color: '#f8f1e6',
    fontSize: 18,
    fontWeight: '800',
  },
  homeWelcomeMeta: {
    color: '#93a982',
    fontSize: 13,
    fontWeight: '700',
  },
  homeHintText: {
    color: '#b9af9f',
    fontSize: 14,
    lineHeight: 20,
  },
  homePropertyList: {
    gap: 10,
  },
  homePropertyCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderRadius: 16,
    backgroundColor: '#24303a',
    borderWidth: 1,
    borderColor: '#3d4e5b',
  },
  homePropertyCopy: {
    flex: 1,
    gap: 4,
  },
  homePropertyTitle: {
    color: '#f8f1e6',
    fontSize: 17,
    fontWeight: '800',
  },
  homePropertyMeta: {
    color: '#b9af9f',
    fontSize: 13,
    lineHeight: 17,
  },
  homePropertyArrow: {
    color: '#d28859',
    fontSize: 24,
    fontWeight: '700',
  },
  settingsSection: {
    gap: 8,
  },
  settingsSectionLabel: {
    color: '#93a982',
    fontSize: 12,
    letterSpacing: 2,
    textTransform: 'uppercase',
    marginTop: 4,
  },
  settingsInfoCard: {
    gap: 4,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 14,
    backgroundColor: '#1f2a33',
    borderWidth: 1,
    borderColor: '#34434f',
  },
  settingsInfoLabel: {
    color: '#93a982',
    fontSize: 12,
    fontWeight: '700',
  },
  settingsInfoValue: {
    color: '#f8f1e6',
    fontSize: 16,
    fontWeight: '700',
    flexShrink: 1,
  },
  settingsRowButton: {
    gap: 4,
    paddingVertical: 13,
    paddingHorizontal: 12,
    borderRadius: 14,
    backgroundColor: '#24303a',
    borderWidth: 1,
    borderColor: '#3d4e5b',
  },
  settingsRowTitle: {
    color: '#f8f1e6',
    fontSize: 16,
    fontWeight: '700',
  },
  settingsRowMeta: {
    color: '#b9af9f',
    fontSize: 12,
    lineHeight: 16,
  },
  settingsDangerCard: {
    gap: 4,
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 14,
    backgroundColor: 'rgba(131, 33, 33, 0.24)',
    borderWidth: 1,
    borderColor: '#b85d4c',
  },
  settingsDangerTitle: {
    color: '#ffcdc5',
    fontSize: 17,
    fontWeight: '800',
  },
  settingsDangerMeta: {
    color: '#f1c0b7',
    fontSize: 13,
    lineHeight: 18,
  },
  propertyHeroCard: {
    gap: 6,
    paddingBottom: 2,
  },
  propertyHeroTitle: {
    color: '#f8f1e6',
    fontSize: 24,
    fontWeight: '800',
  },
  propertyHeroMeta: {
    color: '#b9af9f',
    fontSize: 13,
    lineHeight: 18,
  },
  propertyHeroStats: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  propertyHeroStatChip: {
    borderRadius: 999,
    paddingVertical: 9,
    paddingHorizontal: 14,
    backgroundColor: '#24303a',
    borderWidth: 1,
    borderColor: '#3d4e5b',
  },
  propertyHeroStatText: {
    color: '#93a982',
    fontSize: 13,
    fontWeight: '800',
  },
  card: {
    backgroundColor: 'rgba(38, 50, 61, 0.78)',
    borderRadius: 24,
    padding: 20,
    gap: 10,
    borderWidth: 1,
    borderColor: 'rgba(126, 145, 160, 0.28)',
    shadowColor: '#000000',
    shadowOpacity: 0.2,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
  },
  kicker: {
    color: '#93a982',
    fontSize: 12,
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  title: {
    color: '#f8f1e6',
    fontSize: 30,
    fontWeight: '800',
    textAlign: 'center',
  },
  authPoweredBy: {
    color: '#93a982',
    fontSize: 10,
    letterSpacing: 1.8,
    textTransform: 'uppercase',
    marginTop: -2,
    textAlign: 'center',
  },
  authBrand: {
    color: '#d7c6af',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 2,
    textAlign: 'center',
  },
  authTagline: {
    color: '#dbcbb7',
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 2,
    textAlign: 'center',
  },
  body: {
    color: '#dbcbb7',
    fontSize: 16,
    lineHeight: 24,
  },
  segmentRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 8,
  },
  authModeCard: {
    gap: 6,
    marginTop: 4,
    padding: 12,
    borderRadius: 16,
    backgroundColor: '#24303a',
    borderWidth: 1,
    borderColor: '#3d4e5b',
  },
  authModeTitle: {
    color: '#f8f1e6',
    fontSize: 17,
    fontWeight: '800',
    textAlign: 'center',
  },
  authModeCopy: {
    color: '#dbcbb7',
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
  },
  actionRow: {
    flexDirection: 'row',
    gap: 10,
  },
  visionActionRow: {
    alignItems: 'stretch',
    flexWrap: 'wrap',
  },
  segmentButton: {
    flex: 1,
    borderRadius: 999,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#31404d',
    borderWidth: 1,
    borderColor: '#425563',
  },
  segmentButtonActive: {
    backgroundColor: '#d28859',
    borderColor: '#d28859',
  },
  segmentLabel: {
    color: '#dbcbb7',
    textAlign: 'center',
    fontSize: 15,
    fontWeight: '700',
  },
  segmentLabelActive: {
    color: '#fff7ee',
    textAlign: 'center',
    fontSize: 15,
    fontWeight: '800',
  },
  input: {
    borderRadius: 18,
    backgroundColor: '#31404d',
    borderWidth: 1,
    borderColor: '#425563',
    color: '#f8f1e6',
    fontSize: 17,
    paddingHorizontal: 18,
    paddingVertical: 16,
  },
  passwordWrap: {
    position: 'relative',
  },
  passwordInput: {
    paddingRight: 84,
  },
  eyeButton: {
    position: 'absolute',
    right: 16,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
  },
  eyeButtonText: {
    color: '#f3a56a',
    fontSize: 14,
    fontWeight: '700',
  },
  button: {
    borderRadius: 18,
    paddingVertical: 16,
    paddingHorizontal: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonPrimary: {
    backgroundColor: '#d28859',
  },
  buttonSecondary: {
    backgroundColor: '#31404d',
    borderWidth: 1,
    borderColor: '#425563',
  },
  buttonDisabled: {
    opacity: 0.7,
  },
  buttonDanger: {
    backgroundColor: '#b85d4c',
  },
  buttonText: {
    color: '#fff7ee',
    fontSize: 17,
    fontWeight: '800',
  },
  buttonSecondaryText: {
    color: '#f8f1e6',
    fontSize: 16,
    fontWeight: '700',
  },
  inlineLink: {
    color: '#f3a56a',
    fontSize: 15,
    fontWeight: '700',
  },
  authSecondaryActions: {
    gap: 8,
    alignItems: 'center',
  },
  status: {
    color: '#93a982',
    fontSize: 15,
    lineHeight: 22,
    backgroundColor: 'rgba(124, 162, 127, 0.08)',
    borderRadius: 14,
    padding: 12,
  },
  error: {
    color: '#f0a08e',
    fontSize: 15,
    lineHeight: 22,
    backgroundColor: 'rgba(174, 67, 53, 0.12)',
    borderRadius: 14,
    padding: 12,
  },
  spinner: {
    marginTop: 4,
  },
  label: {
    color: '#93a982',
    fontSize: 12,
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginTop: 8,
  },
  userCard: {
    gap: 4,
    marginTop: 4,
    padding: 16,
    borderRadius: 18,
    backgroundColor: '#31404d',
    borderWidth: 1,
    borderColor: '#425563',
  },
  userCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  userCardCopy: {
    flex: 1,
    gap: 4,
  },
  userName: {
    color: '#f8f1e6',
    fontSize: 20,
    fontWeight: '800',
  },
  userEmail: {
    color: '#dbcbb7',
    fontSize: 15,
  },
  propertyList: {
    gap: 10,
  },
  flexButton: {
    flex: 1,
  },
  chipButton: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: '#24303a',
    borderWidth: 1,
    borderColor: '#3d4e5b',
  },
  chipButtonActive: {
    backgroundColor: '#d28859',
    borderColor: '#d28859',
  },
  chipButtonText: {
    color: '#f8f1e6',
    fontSize: 13,
    fontWeight: '700',
  },
  chipButtonTextActive: {
    color: '#fff7ee',
    fontSize: 13,
    fontWeight: '800',
  },
  settingsCard: {
    gap: 12,
    marginTop: 6,
    padding: 16,
    borderRadius: 18,
    backgroundColor: '#24303a',
    borderWidth: 1,
    borderColor: '#3d4e5b',
  },
  settingsActionList: {
    gap: 10,
  },
  propertyCard: {
    borderRadius: 18,
    padding: 16,
    backgroundColor: '#31404d',
    borderWidth: 1,
    borderColor: '#425563',
    gap: 4,
  },
  propertyCardActive: {
    borderColor: '#d28859',
    backgroundColor: '#3a4752',
  },
  propertyTitle: {
    color: '#f8f1e6',
    fontSize: 18,
    fontWeight: '800',
  },
  propertyMeta: {
    color: '#dbcbb7',
    fontSize: 14,
  },
  workspaceCard: {
    gap: 10,
    marginTop: 4,
    padding: 18,
    borderRadius: 18,
    backgroundColor: '#31404d',
    borderWidth: 1,
    borderColor: '#425563',
  },
  workflowGuideCard: {
    gap: 10,
    padding: 12,
    borderRadius: 16,
    backgroundColor: '#24303a',
    borderWidth: 1,
    borderColor: '#3d4e5b',
  },
  workflowNextCard: {
    gap: 6,
    padding: 12,
    borderRadius: 14,
    backgroundColor: '#3a3128',
    borderWidth: 1,
    borderColor: '#d28859',
  },
  workflowNextLabel: {
    color: '#f0c6a4',
    fontSize: 11,
    letterSpacing: 1,
    textTransform: 'uppercase',
    fontWeight: '700',
  },
  workflowHelperText: {
    color: '#93a982',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  workflowPhaseRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  workflowPhaseChip: {
    gap: 2,
    paddingVertical: 7,
    paddingHorizontal: 10,
    borderRadius: 12,
    backgroundColor: '#1f2a33',
    borderWidth: 1,
    borderColor: '#3d4e5b',
  },
  workflowPhaseChipActive: {
    backgroundColor: '#3f3429',
    borderColor: '#d28859',
  },
  workflowPhaseChipComplete: {
    backgroundColor: '#22342d',
    borderColor: '#4f6b5b',
  },
  workflowPhaseChipLabel: {
    color: '#f8f1e6',
    fontSize: 12,
    fontWeight: '700',
  },
  workflowPhaseChipMeta: {
    color: '#b9af9f',
    fontSize: 11,
  },
  sectionChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 4,
  },
  sectionChip: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: '#24303a',
    borderWidth: 1,
    borderColor: '#3d4e5b',
  },
  sectionChipActive: {
    backgroundColor: '#d28859',
    borderColor: '#d28859',
  },
  sectionChipRecommended: {
    backgroundColor: '#3d3325',
    borderColor: '#d9a14e',
  },
  sectionChipComplete: {
    backgroundColor: '#22342d',
    borderColor: '#4f6b5b',
  },
  sectionChipLabel: {
    color: '#dbcbb7',
    fontSize: 12,
    fontWeight: '700',
  },
  sectionChipLabelRecommended: {
    color: '#f7d7b7',
    fontSize: 12,
    fontWeight: '800',
  },
  sectionChipLabelActive: {
    color: '#fff7ee',
    fontSize: 12,
    fontWeight: '800',
  },
  sectionPanel: {
    gap: 12,
    marginTop: 8,
  },
  workspaceHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  workspaceHeaderCopy: {
    flex: 1,
    gap: 4,
  },
  collapseButton: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: '#24303a',
    borderWidth: 1,
    borderColor: '#3d4e5b',
  },
  collapseButtonText: {
    color: '#f8f1e6',
    fontSize: 13,
    fontWeight: '700',
  },
  pricingCard: {
    gap: 6,
    marginTop: 2,
    padding: 14,
    borderRadius: 16,
    backgroundColor: '#24303a',
    borderWidth: 1,
    borderColor: '#3d4e5b',
  },
  priceBand: {
    color: '#fff7ee',
    fontSize: 26,
    fontWeight: '800',
    lineHeight: 34,
  },
  overviewInsightCard: {
    gap: 8,
    padding: 14,
    borderRadius: 16,
    backgroundColor: '#24303a',
    borderWidth: 1,
    borderColor: '#3d4e5b',
  },
  summaryBulletList: {
    gap: 8,
  },
  summaryBullet: {
    color: '#dbcbb7',
    fontSize: 14,
    lineHeight: 20,
  },
  captureCard: {
    gap: 12,
    marginTop: 8,
    paddingTop: 4,
  },
  galleryCard: {
    gap: 12,
    marginTop: 8,
    paddingTop: 4,
  },
  roomChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  roomChip: {
    minWidth: 92,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 18,
    backgroundColor: '#31404d',
    borderWidth: 1,
    borderColor: '#425563',
  },
  roomChipActive: {
    backgroundColor: '#d28859',
    borderColor: '#d28859',
  },
  roomChipRecommended: {
    backgroundColor: '#3d3325',
    borderColor: '#d9a14e',
  },
  roomChipDone: {
    backgroundColor: '#22342d',
    borderColor: '#4f6b5b',
  },
  roomChipLabel: {
    color: '#dbcbb7',
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  roomChipLabelActive: {
    color: '#fff7ee',
    fontSize: 14,
    fontWeight: '800',
    textAlign: 'center',
  },
  roomChipLabelDone: {
    color: '#d8ead8',
    fontSize: 14,
    fontWeight: '800',
    textAlign: 'center',
  },
  photoPreviewCard: {
    gap: 12,
    padding: 14,
    borderRadius: 16,
    backgroundColor: '#24303a',
    borderWidth: 1,
    borderColor: '#3d4e5b',
  },
  photoPreview: {
    width: '100%',
    height: 220,
    borderRadius: 14,
    backgroundColor: '#1b252d',
  },
  galleryRail: {
    gap: 12,
    paddingVertical: 2,
  },
  galleryTile: {
    width: 108,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#24303a',
    borderWidth: 1,
    borderColor: '#3d4e5b',
  },
  galleryTileActive: {
    borderColor: '#d28859',
  },
  galleryTileImage: {
    width: '100%',
    aspectRatio: 1,
    backgroundColor: '#1b252d',
  },
  galleryTileLabel: {
    color: '#f8f1e6',
    fontSize: 13,
    fontWeight: '700',
    paddingHorizontal: 10,
    paddingTop: 10,
  },
  galleryTileTag: {
    color: '#d28859',
    fontSize: 11,
    fontWeight: '700',
    paddingHorizontal: 10,
    paddingBottom: 10,
  },
  selectedAssetCard: {
    gap: 10,
    padding: 14,
    borderRadius: 16,
    backgroundColor: '#24303a',
    borderWidth: 1,
    borderColor: '#3d4e5b',
  },
  selectedAssetImage: {
    width: '100%',
    height: 220,
    borderRadius: 14,
    backgroundColor: '#1b252d',
  },
  selectedAssetTitle: {
    color: '#f8f1e6',
    fontSize: 18,
    fontWeight: '800',
  },
  selectedAssetMeta: {
    color: '#dbcbb7',
    fontSize: 14,
    lineHeight: 20,
  },
  assetScore: {
    color: '#93a982',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
  },
  listingCandidateTag: {
    color: '#93a982',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  preferredVariantTag: {
    color: '#d28859',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  variantSummary: {
    color: '#f8f1e6',
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '700',
  },
  variantHint: {
    color: '#dbcbb7',
    fontSize: 13,
    lineHeight: 20,
  },
  noteInput: {
    minHeight: 90,
    textAlignVertical: 'top',
  },
  coverageList: {
    gap: 10,
  },
  coverageRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 14,
    backgroundColor: '#24303a',
    borderWidth: 1,
    borderColor: '#3d4e5b',
  },
  coverageRoom: {
    color: '#f8f1e6',
    fontSize: 15,
    fontWeight: '700',
  },
  coverageDone: {
    color: '#93a982',
    fontSize: 14,
    fontWeight: '700',
  },
  coverageMissing: {
    color: '#f0a08e',
    fontSize: 14,
    fontWeight: '700',
  },
  candidateList: {
    gap: 10,
  },
  candidateCard: {
    flexDirection: 'row',
    gap: 12,
    padding: 14,
    borderRadius: 16,
    backgroundColor: '#24303a',
    borderWidth: 1,
    borderColor: '#3d4e5b',
  },
  candidateRank: {
    color: '#d28859',
    fontSize: 18,
    fontWeight: '800',
    minWidth: 28,
  },
  candidateCopy: {
    flex: 1,
    gap: 4,
  },
  candidateTitle: {
    color: '#f8f1e6',
    fontSize: 16,
    fontWeight: '800',
  },
  candidateMeta: {
    color: '#dbcbb7',
    fontSize: 14,
    lineHeight: 20,
  },
  candidateSelectedTag: {
    color: '#93a982',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  visionPanel: {
    gap: 12,
    padding: 14,
    borderRadius: 16,
    backgroundColor: '#24303a',
    borderWidth: 1,
    borderColor: '#3d4e5b',
  },
  learnMoreButton: {
    alignSelf: 'flex-start',
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: '#24303a',
    borderWidth: 1,
    borderColor: '#3d4e5b',
  },
  learnMoreButtonText: {
    color: '#93a982',
    fontSize: 13,
    fontWeight: '700',
  },
  visionJobCard: {
    gap: 8,
    padding: 12,
    borderRadius: 14,
    backgroundColor: '#31404d',
    borderWidth: 1,
    borderColor: '#425563',
  },
  visionJobHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  visionJobTitle: {
    color: '#f8f1e6',
    fontSize: 15,
    fontWeight: '800',
  },
  visionActionButton: {
    minWidth: 0,
  },
  visionActionButtonText: {
    fontSize: 15,
    textAlign: 'center',
  },
  visionImage: {
    width: '100%',
    height: 220,
    borderRadius: 14,
    backgroundColor: '#1b252d',
  },
  effectList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  effectChip: {
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#22303a',
    borderWidth: 1,
    borderColor: '#3d4e5b',
  },
  effectChipText: {
    color: '#d28859',
    fontSize: 12,
    fontWeight: '700',
  },
  variantList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  taskList: {
    gap: 10,
  },
  taskSummaryCard: {
    gap: 6,
    padding: 14,
    borderRadius: 16,
    backgroundColor: '#2c3440',
    borderWidth: 1,
    borderColor: '#d28859',
  },
  taskSummaryValue: {
    color: '#fff7ee',
    fontSize: 26,
    fontWeight: '800',
  },
  taskSummaryText: {
    color: '#dbcbb7',
    fontSize: 14,
    lineHeight: 20,
  },
  taskCard: {
    gap: 6,
    padding: 14,
    borderRadius: 16,
    backgroundColor: '#24303a',
    borderWidth: 1,
    borderColor: '#3d4e5b',
  },
  taskCardWorking: {
    borderColor: '#d9a14e',
    borderLeftWidth: 4,
    backgroundColor: '#2d3336',
  },
  taskCardComplete: {
    opacity: 0.76,
  },
  taskMetaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  taskDone: {
    color: '#93a982',
    fontSize: 12,
    letterSpacing: 1,
    textTransform: 'uppercase',
    fontWeight: '800',
  },
  taskOpen: {
    color: '#d28859',
    fontSize: 12,
    letterSpacing: 1,
    textTransform: 'uppercase',
    fontWeight: '800',
  },
  taskWorking: {
    color: '#e3b453',
    fontSize: 12,
    letterSpacing: 1,
    textTransform: 'uppercase',
    fontWeight: '800',
  },
  taskCategory: {
    color: '#b9af9f',
    fontSize: 12,
    textTransform: 'capitalize',
  },
  taskTitle: {
    color: '#f8f1e6',
    fontSize: 16,
    fontWeight: '800',
  },
  taskDetail: {
    color: '#dbcbb7',
    fontSize: 14,
    lineHeight: 20,
  },
  taskActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  taskActionChip: {
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#425563',
    backgroundColor: '#31404d',
  },
  taskActionChipActive: {
    backgroundColor: '#d28859',
    borderColor: '#d28859',
  },
  taskActionChipText: {
    color: '#dbcbb7',
    fontSize: 13,
    fontWeight: '700',
  },
  taskActionChipTextActive: {
    color: '#fff7ee',
    fontSize: 13,
    fontWeight: '800',
  },
  taskStatusButton: {
    alignSelf: 'flex-start',
    marginTop: 6,
  },
  completedTasksCard: {
    gap: 10,
    padding: 14,
    borderRadius: 16,
    backgroundColor: '#1f2a33',
    borderWidth: 1,
    borderColor: '#34434f',
  },
  completedTasksToggle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  completedTasksTitle: {
    color: '#f8f1e6',
    fontSize: 15,
    fontWeight: '800',
  },
  completedTasksToggleText: {
    color: '#93a982',
    fontSize: 13,
    fontWeight: '700',
  },
  customTaskComposer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 12,
    borderRadius: 16,
    backgroundColor: '#24303a',
    borderWidth: 1,
    borderColor: '#3d4e5b',
  },
  customTaskInput: {
    flex: 1,
    backgroundColor: '#31404d',
    marginBottom: 0,
  },
  customTaskButton: {
    minWidth: 108,
  },
  authFooter: {
    gap: 8,
    alignItems: 'center',
    paddingBottom: 2,
  },
  authFooterDock: {
    borderTopWidth: 1,
    borderTopColor: 'rgba(126, 145, 160, 0.18)',
    backgroundColor: 'rgba(22, 32, 39, 0.98)',
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: Platform.OS === 'android' ? 14 : 8,
  },
  authFooterCopy: {
    color: '#b9af9f',
    fontSize: 11,
    textAlign: 'center',
  },
  authFooterLinks: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 16,
  },
  authFooterLink: {
    color: '#93a982',
    fontSize: 11,
    fontWeight: '700',
  },
  mobileFooter: {
    color: '#8f9aa0',
    fontSize: 12,
    textAlign: 'center',
  },
  mobileFooterDock: {
    borderTopWidth: 1,
    borderTopColor: 'rgba(126, 145, 160, 0.18)',
    backgroundColor: 'rgba(22, 32, 39, 0.98)',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
});

