services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: workside-home-seller
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'

  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  mongo-data:
