const REPLICATE_INPAINT_MODEL =
  'lucataco/sdxl-inpainting:a5b13068cc81a89a4fbeefeccc774869fcb34df4dbc92c1555e0f2771d49dde7';

export const VISION_PRESETS = [
  {
    key: 'enhance_listing_quality',
    legacyKeys: [],
    displayName: 'Improve Photo',
    shortLabel: 'Enhanced',
    category: 'enhancement',
    roomCompatibility: ['kitchen', 'living_room', 'bedroom', 'bathroom', 'exterior', 'unknown'],
    providerPreference: 'local_sharp_only',
    promptVersion: 1,
    outputCount: 1,
    disclaimerType: 'truthful_enhancement',
    recommendedUse: ['brochure', 'report'],
    upgradeTier: 'standard',
    basePrompt:
      'Enhance this real estate photo for listing use. Improve brightness, clarity, and overall presentation while preserving the true structure, layout, and finishes of the room. Keep the image realistic, natural, and honest. Do not invent architectural features or remove major permanent elements.',
    helperText:
      'Quick listing-safe enhancement that improves brightness, clarity, and presentation while keeping the room realistic.',
  },
  {
    key: 'lighting_boost',
    legacyKeys: [],
    displayName: 'Lighting Boost',
    shortLabel: 'Lighting',
    internalOnly: true,
    category: 'enhancement',
    roomCompatibility: ['kitchen', 'living_room', 'bedroom', 'bathroom', 'exterior', 'unknown'],
    providerPreference: 'local_sharp_only',
    promptVersion: 1,
    outputCount: 1,
    disclaimerType: 'truthful_enhancement',
    recommendedUse: ['brochure', 'report'],
    upgradeTier: 'standard',
    basePrompt:
      'Improve this real estate photo with a lighting-first enhancement. Lift dark areas, balance bright windows, and make the room read cleaner and brighter while preserving the true structure, layout, finishes, and furnishings. Keep the image realistic and honest.',
    helperText:
      'Recover darker rooms with a lighting-first pass before stronger enhancement or listing polish.',
  },
  {
    key: 'declutter_light',
    legacyKeys: ['declutter_preview'],
    displayName: 'Light Declutter',
    internalOnly: true,
    shortLabel: 'Declutter',
    category: 'enhancement',
    roomCompatibility: ['kitchen', 'living_room', 'bedroom', 'bathroom', 'unknown'],
    providerPreference: 'replicate',
    promptVersion: 1,
    outputCount: 2,
    disclaimerType: 'truthful_enhancement',
    recommendedUse: ['brochure', 'report'],
    upgradeTier: 'standard',
    basePrompt:
      'Clean up this residential interior photo for real estate listing use. Remove small movable distractions such as loose throws, remotes, cords, papers, small decor clusters, shelf clutter, table clutter, and floor-edge clutter. Preserve the main furniture, rug, windows, walls, flooring, lamps, shelving, architecture, and room layout. Make the room visibly tidier and more buyer-friendly while staying realistic.',
    helperText:
      'Reduce small distractions and improve presentation while keeping the room believable.',
    strength: 0.68,
    guidanceScale: 7.9,
    numInferenceSteps: 34,
    negativePrompt:
      'changed windows, changed walls, changed flooring, changed rug, new furniture, restaging, empty room, warped furniture, distorted architecture, fake geometry, unrealistic shadows, blurry, low quality',
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
  {
    key: 'declutter_medium',
    legacyKeys: [],
    displayName: 'Clean Up Photo',
    shortLabel: 'Prep Plan',
    category: 'enhancement',
    roomCompatibility: ['kitchen', 'living_room', 'bedroom', 'bathroom', 'unknown'],
    providerPreference: 'replicate',
    promptVersion: 1,
    outputCount: 3,
    disclaimerType: 'truthful_enhancement',
    recommendedUse: ['report'],
    upgradeTier: 'standard',
    basePrompt:
      'Create a visibly cleaner listing-photo version of this residential interior. Remove loose throws and blankets, remotes, cords, papers, small decor clusters, shelf clutter, table clutter, and floor-edge clutter. Simplify visually noisy surfaces and make the room read cleaner at thumbnail size. In living rooms, clean the sofa throw area, shelf decor clusters, side-table objects, coffee-table distractions, and small loose items. Preserve major furniture, windows, walls, flooring, rug, lamps, built-ins, architecture, lighting direction, and room layout. Do not fully empty or restage the room.',
    helperText:
      'Review visible distractions and create a practical seller prep plan. AI cleanup can be enabled after provider quality is validated.',
    strength: 0.82,
    guidanceScale: 8.6,
    numInferenceSteps: 42,
    negativePrompt:
      'changed windows, changed walls, changed flooring, changed rug, new furniture, full restaging, empty room, warped furniture, distorted architecture, fake geometry, unrealistic shadows, blurry, low quality',
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
  {
    key: 'remove_furniture',
    legacyKeys: [],
    displayName: 'Open Room Preview',
    shortLabel: 'Open Room',
    category: 'concept_preview',
    roomCompatibility: ['kitchen', 'living_room', 'bedroom', 'bathroom', 'exterior', 'unknown'],
    providerPreference: 'replicate',
    promptVersion: 9,
    outputCount: 3,
    disclaimerType: 'concept_preview',
    recommendedUse: ['report'],
    upgradeTier: 'premium',
    basePrompt:
      'Create a realistic open-room concept preview for this real estate photo. Remove or simplify movable furniture and visual distractions when it can be done believably. Prioritize clearing portable seating, small tables, decor, throws, clutter, and bulky visual distractions while preserving the true room architecture. Keep windows, blinds, trim, ceiling lines, baseboards, built-ins, doors, permanent fixtures, lighting direction, and perspective intact. The room should feel more open and easier to understand, but must remain realistic.',
    helperText:
      'Create a concept preview that makes the room feel more open while preserving structural truth.',
    strength: 0.76,
    guidanceScale: 7.8,
    numInferenceSteps: 38,
    negativePrompt:
      'warped windows, distorted blinds, changed windows, altered trim, changed ceiling, changed wall geometry, changed floor perspective, fake architecture, added furniture, new staging, unrealistic shadows, blurry, low quality',
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
  {
    key: 'cleanup_empty_room',
    legacyKeys: [],
    displayName: 'Open Room Cleanup',
    internalOnly: true,
    shortLabel: 'Open Cleanup',
    category: 'concept_preview',
    roomCompatibility: ['kitchen', 'living_room', 'bedroom', 'bathroom', 'exterior', 'unknown'],
    providerPreference: 'replicate',
    promptVersion: 1,
    outputCount: 3,
    disclaimerType: 'concept_preview',
    recommendedUse: ['report'],
    upgradeTier: 'premium',
    basePrompt:
      'Refine an open-room concept preview. Reduce leftover visual fragments, small distractions, uneven floor transitions, and rough wall or trim edges. Preserve architecture, built-ins, shelving, windows, doors, flooring direction, and room perspective. Add nothing new. Keep the room believable, clean, and presentation-ready.',
    helperText:
      'Run a lighter cleanup pass on an open-room concept without redesigning the room.',
    strength: 0.78,
    guidanceScale: 8.5,
    numInferenceSteps: 34,
    negativePrompt:
      'new furniture, extra decor, fireplace, mantel, added shelving, added built-ins, new objects, unrealistic geometry, warped lines, distorted walls, overdesigned room',
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
  {
    key: 'paint_warm_neutral',
    legacyKeys: [],
    displayName: 'Warm Walls',
    shortLabel: 'Warm Walls',
    category: 'concept_preview',
    roomCompatibility: ['kitchen', 'living_room', 'bedroom', 'bathroom', 'dining_room', 'office', 'unknown'],
    providerPreference: 'local_sharp_only',
    promptVersion: 11,
    outputCount: 1,
    disclaimerType: 'concept_preview',
    recommendedUse: ['report'],
    upgradeTier: 'premium',
    basePrompt:
      'Change the wall color to a clearly warmer beige, cream, or soft taupe tone. The difference must be immediately noticeable at first glance. Avoid subtle or barely visible changes. Ensure the wall color shift is visually obvious without needing comparison. Only modify painted wall surfaces. Do NOT add any new objects, fixtures, radiators, vents, framed art, sconces, or architectural elements. Preserve trim, ceilings, windows, built-ins, flooring, furniture, layout, shadows, and natural lighting. Keep the image realistic and suitable for showing a paint-direction concept only.',
    helperText:
      'Preview a warmer wall direction without changing the room structure.',
    strength: 0.96,
    guidanceScale: 9,
    numInferenceSteps: 48,
    negativePrompt:
      'added furniture, new staging, radiator, heater, vent cover, wall art, framed art, picture frames, decor, wall sconces, fixtures, paneling, molding, changed flooring, changed trim color, changed ceiling color, altered windows, altered built-ins, unrealistic geometry, warped walls, low quality',
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
  {
    key: 'paint_bright_white',
    legacyKeys: [],
    displayName: 'Brighten Walls',
    internalOnly: true,
    shortLabel: 'Brighten Walls',
    category: 'concept_preview',
    roomCompatibility: ['kitchen', 'living_room', 'bedroom', 'bathroom', 'dining_room', 'office', 'unknown'],
    providerPreference: 'local_sharp_only',
    promptVersion: 12,
    outputCount: 1,
    disclaimerType: 'concept_preview',
    recommendedUse: ['report'],
    upgradeTier: 'premium',
    basePrompt:
      'Brighten the painted walls to a clean, bright white tone suitable for real estate listing photos. The change must be immediately noticeable at first glance. Ensure the wall color shift is visually obvious without needing comparison. CRITICAL: only modify painted wall surfaces. Do NOT add any new objects, fixtures, radiators, vents, framed art, sconces, or architectural elements. Do NOT change flooring, windows, trim, shelving, or furniture. Preserve all shadows, natural lighting direction, wall texture, and sharp edges without smoothing or blurring. Do NOT alter window brightness or outdoor scenery. This must look like the SAME walls freshly painted bright white, not edited or artificial.',
    helperText:
      'Show a brighter wall direction for a cleaner, airier feel.',
    strength: 0.98,
    guidanceScale: 9.4,
    numInferenceSteps: 54,
    negativePrompt:
      'added furniture, new staging, bed, bench, sofa, chair, chandelier, pendant light, wall art, framed art, picture frames, radiator, heater, vent cover, wall sconces, wall paneling, wainscoting, changed flooring, changed trim color, changed ceiling color, altered windows, altered built-ins, unrealistic geometry, warped walls, blurry paint edges, blurred wall texture, changed window brightness, altered outdoor scenery, low quality',
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
  {
    key: 'paint_soft_greige',
    legacyKeys: [],
    displayName: 'Soft Greige Walls',
    internalOnly: true,
    shortLabel: 'Greige Paint',
    category: 'concept_preview',
    roomCompatibility: ['kitchen', 'living_room', 'bedroom', 'bathroom', 'dining_room', 'office', 'unknown'],
    providerPreference: 'local_sharp_only',
    promptVersion: 11,
    outputCount: 1,
    disclaimerType: 'concept_preview',
    recommendedUse: ['report'],
    upgradeTier: 'premium',
    basePrompt:
      'Change the wall color to a clearly visible soft greige tone that feels modern and buyer-friendly. The difference must be immediately noticeable at first glance. Avoid subtle or barely visible changes. Ensure the wall color shift is visually obvious without needing comparison. Only modify painted wall surfaces. Do NOT add any new objects, fixtures, radiators, vents, framed art, sconces, or architectural elements. Preserve the room’s true structure, trim, flooring, furniture, layout, shadows, and natural lighting. Keep the output realistic and suitable for listing-planning visualization.',
    helperText:
      'Preview a softer designer-neutral wall direction.',
    strength: 0.96,
    guidanceScale: 9,
    numInferenceSteps: 48,
    negativePrompt:
      'added furniture, new staging, changed flooring, changed trim color, changed ceiling color, altered windows, altered built-ins, unrealistic geometry, warped walls, low quality',
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
  {
    key: 'paint_dark_charcoal_test',
    legacyKeys: [],
    displayName: 'Statement Wall Color Test',
    internalOnly: true,
    shortLabel: 'Statement Test',
    category: 'concept_preview',
    roomCompatibility: ['kitchen', 'living_room', 'bedroom', 'bathroom', 'dining_room', 'office', 'unknown'],
    providerPreference: 'replicate',
    promptVersion: 1,
    outputCount: 1,
    disclaimerType: 'concept_preview',
    recommendedUse: ['report'],
    upgradeTier: 'premium',
    basePrompt:
      'Repaint all visible painted walls in a bold, dark, statement-making color concept directed by the seller instructions. The result must be dramatic, high-contrast, and immediately obvious at first glance. Apply a strong, uniform coat across the wall surfaces and do not preserve the original light wall tone. Maintain realistic lighting, shadows, wall texture, trim, windows, ceilings, built-ins, and room geometry. Only modify painted wall surfaces and do not change the room structure.',
    helperText:
      'A hard-contrast wall-color test that proves the pipeline can deliver an obvious paint change.',
    strength: 0.95,
    guidanceScale: 9.5,
    numInferenceSteps: 55,
    negativePrompt:
      'furniture changes, decor changes, new objects, lighting changes, altered windows, changed flooring, changed trim color, unrealistic geometry, warped walls, low quality',
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
    {
      key: 'floor_light_wood',
      legacyKeys: [],
      displayName: 'Lighten Floors',
      shortLabel: 'Lighten Floors',
      category: 'concept_preview',
      roomCompatibility: ['living_room', 'bedroom', 'dining_room', 'office', 'unknown'],
      providerPreference: 'local_sharp_only',
      promptVersion: 9,
    outputCount: 1,
    disclaimerType: 'concept_preview',
    recommendedUse: ['report'],
    upgradeTier: 'premium',
    basePrompt:
      'Create a realistic preview where ONLY the existing hardwood flooring is lightened to a natural light oak or blonde wood tone. Maintain the exact same plank layout, seams, spacing, and direction. Preserve natural wood grain texture and keep the same floorboards sharp and aligned with the room perspective. Do NOT introduce carpet, tile, stone, rugs, or any new flooring material. Do NOT blur or smear plank edges. Preserve walls, baseboards, lighting, shadows, shelving, windows, and room geometry exactly. This must look like the SAME floor, just refinished lighter.',
    helperText:
      'Preview a lighter floor direction to brighten the room.',
    strength: 0.95,
    guidanceScale: 9,
    numInferenceSteps: 44,
    negativePrompt:
      'carpet texture, rug, tile, stone, pattern overlay, blurry wood grain, smeared wood grain, warped planks, distorted lines, uneven flooring, patchy floor, patchy flooring, fake material replacement, low quality, unrealistic geometry',
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
    {
      key: 'floor_medium_wood',
      legacyKeys: [],
      displayName: 'Warm Floors',
      internalOnly: true,
      shortLabel: 'Warm Floors',
      category: 'concept_preview',
      roomCompatibility: ['living_room', 'bedroom', 'dining_room', 'office', 'unknown'],
      providerPreference: 'local_sharp_only',
      promptVersion: 7,
    outputCount: 1,
    disclaimerType: 'concept_preview',
    recommendedUse: ['report'],
    upgradeTier: 'premium',
    basePrompt:
      'Create a conceptual preview of this room with the flooring shifted toward a warmer medium-tone direction that feels inviting, modern, and buyer-friendly. Preserve the room structure, layout, baseboards, and perspective. Keep the output realistic and appropriate for planning visualization rather than exact material simulation.',
    helperText:
      'Preview a warmer floor direction for a more inviting feel.',
    strength: 0.95,
    guidanceScale: 9,
    numInferenceSteps: 44,
    negativePrompt:
      'carpet texture, rug pattern, patchy flooring, smeared wood grain, warped floor lines, low quality, unrealistic geometry',
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
    {
      key: 'floor_dark_hardwood',
      legacyKeys: [],
      displayName: 'Darken Floors',
      internalOnly: true,
      shortLabel: 'Darken Floors',
      category: 'concept_preview',
      roomCompatibility: ['living_room', 'bedroom', 'dining_room', 'office', 'unknown'],
      providerPreference: 'local_sharp_only',
      promptVersion: 8,
    outputCount: 1,
    disclaimerType: 'concept_preview',
    recommendedUse: ['report'],
    upgradeTier: 'premium',
    basePrompt:
      'Create a conceptual preview of this room with the flooring shifted to a clearly darker, richer direction so the floor reads noticeably deeper and more upscale than the source image. Preserve room proportions, baseboards, walls, furniture perspective, reflections, and architecture. Keep the output realistic and clearly a planning concept, not an exact install preview.',
    helperText:
      'Preview a darker floor direction with more contrast and richness.',
    strength: 0.97,
    guidanceScale: 9.6,
    numInferenceSteps: 50,
    negativePrompt:
      'light blonde floor, unchanged flooring color, subtle floor shift, carpet texture, rug pattern, patchy flooring, smeared wood grain, warped floor lines, low quality, unrealistic geometry',
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
    {
      key: 'floor_lvp_neutral',
      legacyKeys: [],
      displayName: 'Neutralize Floors',
      internalOnly: true,
      shortLabel: 'Neutralize Floors',
      category: 'concept_preview',
      roomCompatibility: ['living_room', 'bedroom', 'dining_room', 'office', 'kitchen', 'unknown'],
      providerPreference: 'local_sharp_only',
      promptVersion: 7,
    outputCount: 1,
    disclaimerType: 'concept_preview',
    recommendedUse: ['report'],
    upgradeTier: 'premium',
    basePrompt:
      'Create a conceptual preview of this room with the flooring shifted toward a more neutral, broadly buyer-friendly finish direction. Preserve architecture, cabinetry, appliances, room proportions, and floor perspective. Keep the image realistic and suitable as a concept only, not an exact material match.',
    helperText:
      'Preview a more neutral floor direction for broader buyer appeal.',
    strength: 0.95,
    guidanceScale: 9,
    numInferenceSteps: 44,
    negativePrompt:
      'carpet texture, rug pattern, patchy flooring, smeared plank texture, warped floor lines, low quality, unrealistic geometry',
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
  {
    key: 'floor_tile_stone',
    legacyKeys: [],
    displayName: 'Tile / Stone Floors',
    internalOnly: true,
    shortLabel: 'Tile / Stone',
    hiddenFromCatalog: true,
    category: 'concept_preview',
    roomCompatibility: ['kitchen', 'bathroom', 'living_room', 'dining_room', 'exterior', 'unknown'],
    providerPreference: 'replicate',
    promptVersion: 12,
    outputCount: 1,
    disclaimerType: 'concept_preview',
    recommendedUse: ['report'],
    upgradeTier: 'premium',
    basePrompt:
      'Completely replace the floor material with realistic stone or ceramic tile flooring. The new floor must follow the exact perspective, depth, and geometry of the original floor. Preserve lighting, shadows, and reflections from the original image. Generate natural tile layout with consistent spacing and visible grout lines that align with the room perspective. Do NOT overlay patterns. Do NOT create flat textures. The floor must appear physically integrated into the scene. Do NOT modify walls, windows, shelving, or furniture.',
    helperText:
      'Preview a tile or stone floor upgrade for kitchens, baths, or exterior surfaces.',
    strength: 0.65,
    guidanceScale: 8.2,
    numInferenceSteps: 60,
    negativePrompt:
      'wood texture, wood grain, laminate, glossy wood, overlay texture, flat pattern, repeating pattern, stencil pattern, warped perspective, floating texture, inconsistent lighting, distorted floor lines, warped tiles, uneven grid, blurry surface',
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
  {
    key: 'kitchen_white_cabinets_granite',
    legacyKeys: [],
    displayName: 'Kitchen Preview',
    shortLabel: 'White Kitchen',
    category: 'concept_preview',
    roomCompatibility: ['kitchen', 'unknown'],
    providerPreference: 'replicate',
    promptVersion: 2,
    outputCount: 2,
    disclaimerType: 'concept_preview',
    recommendedUse: ['report'],
    upgradeTier: 'premium',
    basePrompt:
      'Create a conceptual kitchen upgrade preview with cabinets repainted a crisp white and countertops shown as clean granite. Preserve the real cabinet layout, appliance positions, backsplash alignment, sink, windows, and room geometry. Keep the result realistic and clearly a planning concept.',
    helperText:
      'Preview a brighter kitchen refresh with white cabinetry and granite counters.',
    strength: 0.84,
    guidanceScale: 8,
    numInferenceSteps: 40,
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
  {
    key: 'kitchen_white_cabinets_quartz',
    legacyKeys: [],
    displayName: 'White Cabinets + Quartz',
    internalOnly: true,
    shortLabel: 'White + Quartz',
    category: 'concept_preview',
    roomCompatibility: ['kitchen', 'unknown'],
    providerPreference: 'replicate',
    promptVersion: 2,
    outputCount: 2,
    disclaimerType: 'concept_preview',
    recommendedUse: ['report'],
    upgradeTier: 'premium',
    basePrompt:
      'Create a conceptual kitchen upgrade preview with cabinets repainted a crisp white and countertops shown as clean quartz. Preserve the real cabinet layout, appliance positions, backsplash alignment, sink, windows, and room geometry. Keep the result realistic and clearly a planning concept.',
    helperText:
      'Preview a brighter kitchen refresh with white cabinetry and quartz counters.',
    strength: 0.84,
    guidanceScale: 8,
    numInferenceSteps: 40,
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
  {
    key: 'kitchen_green_cabinets_granite',
    legacyKeys: [],
    displayName: 'Green Cabinets + Granite',
    internalOnly: true,
    shortLabel: 'Green Kitchen',
    category: 'concept_preview',
    roomCompatibility: ['kitchen', 'unknown'],
    providerPreference: 'replicate',
    promptVersion: 2,
    outputCount: 2,
    disclaimerType: 'concept_preview',
    recommendedUse: ['report'],
    upgradeTier: 'premium',
    basePrompt:
      'Create a conceptual kitchen upgrade preview with cabinets repainted a refined sage or deep green tone and countertops shown as elegant granite. Preserve cabinet alignment, countertop edges, appliances, backsplash, sink, windows, and true room geometry. Keep the result realistic and clearly a planning concept.',
    helperText:
      'Preview a designer kitchen update with green cabinetry and granite counters.',
    strength: 0.84,
    guidanceScale: 8,
    numInferenceSteps: 40,
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
  {
    key: 'kitchen_green_cabinets_quartz',
    legacyKeys: [],
    displayName: 'Green Cabinets + Quartz',
    internalOnly: true,
    shortLabel: 'Green + Quartz',
    category: 'concept_preview',
    roomCompatibility: ['kitchen', 'unknown'],
    providerPreference: 'replicate',
    promptVersion: 2,
    outputCount: 2,
    disclaimerType: 'concept_preview',
    recommendedUse: ['report'],
    upgradeTier: 'premium',
    basePrompt:
      'Create a conceptual kitchen upgrade preview with cabinets repainted a refined sage or deep green tone and countertops shown as elegant quartz. Preserve cabinet alignment, countertop edges, appliances, backsplash, sink, windows, and true room geometry. Keep the result realistic and clearly a planning concept.',
    helperText:
      'Preview a designer kitchen update with green cabinetry and quartz counters.',
    strength: 0.84,
    guidanceScale: 8,
    numInferenceSteps: 40,
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
  {
    key: 'exterior_curb_appeal_refresh',
    legacyKeys: [],
    displayName: 'Curb Appeal Refresh',
    shortLabel: 'Curb Appeal',
    category: 'concept_preview',
    roomCompatibility: ['exterior', 'unknown'],
    providerPreference: 'replicate',
    promptVersion: 2,
    outputCount: 2,
    disclaimerType: 'concept_preview',
    recommendedUse: ['report'],
    upgradeTier: 'premium',
    basePrompt:
      'Create a conceptual curb-appeal upgrade preview for this exterior photo with refreshed landscaping, cleaner planting beds, improved pathway lighting or fixtures, and stronger first-impression presentation. Preserve the home structure, roofline, windows, doors, driveway, and lot boundaries. Keep the result realistic and clearly a planning concept.',
    helperText:
      'Preview stronger front-exterior landscaping and fixture upgrades.',
    strength: 0.82,
    guidanceScale: 8,
    numInferenceSteps: 40,
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
  {
    key: 'backyard_entertaining_refresh',
    legacyKeys: [],
    displayName: 'Backyard Entertaining Refresh',
    internalOnly: true,
    shortLabel: 'Backyard Refresh',
    category: 'concept_preview',
    roomCompatibility: ['exterior', 'unknown'],
    providerPreference: 'replicate',
    promptVersion: 2,
    outputCount: 2,
    disclaimerType: 'concept_preview',
    recommendedUse: ['report'],
    upgradeTier: 'premium',
    basePrompt:
      'Create a conceptual backyard upgrade preview with more intentional plants, cleaner hardscape, refreshed fixtures or lighting, and a more inviting entertaining feel. Preserve fences, lot boundaries, house structure, patio geometry, and true exterior layout. Keep the result realistic and suitable for planning visualization.',
    helperText:
      'Preview a more polished backyard with plants, fixtures, and entertaining appeal.',
    strength: 0.82,
    guidanceScale: 8,
    numInferenceSteps: 40,
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
  {
    key: 'backyard_pool_preview',
    legacyKeys: [],
    displayName: 'Pool / Water Feature Preview',
    internalOnly: true,
    shortLabel: 'Pool Concept',
    category: 'concept_preview',
    roomCompatibility: ['exterior', 'unknown'],
    providerPreference: 'replicate',
    promptVersion: 2,
    outputCount: 2,
    disclaimerType: 'concept_preview',
    recommendedUse: ['report'],
    upgradeTier: 'premium',
    basePrompt:
      'Create a conceptual backyard planning preview that adds a tasteful pool or water-feature concept while preserving the home, yard boundaries, patio geometry, and overall lot shape. Keep the water feature proportional, realistic, and clearly suitable for budget-planning discussion rather than representing an existing improvement.',
    helperText:
      'Preview a future pool or water-feature concept for the backyard.',
    strength: 0.84,
    guidanceScale: 8,
    numInferenceSteps: 40,
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
  {
    key: 'combined_listing_refresh',
    legacyKeys: [],
    displayName: 'Listing Refresh',
    internalOnly: true,
    shortLabel: 'Refresh',
    category: 'enhancement',
    roomCompatibility: ['kitchen', 'living_room', 'bedroom', 'bathroom', 'exterior', 'unknown'],
    providerPreference: 'local_sharp_only',
    promptVersion: 1,
    outputCount: 1,
    disclaimerType: 'truthful_enhancement',
    recommendedUse: ['brochure', 'report'],
    upgradeTier: 'standard',
    basePrompt:
      'Transform this room photo into a cleaner, brighter, more listing-ready version. Improve lighting, reduce clutter, and create a polished real-estate-photo feel while preserving the room’s true structure, layout, and finishes. Keep the image realistic and honest.',
    helperText:
      'Blend enhancement and cleanup into a more polished listing-ready image.',
  },
];

const LEGACY_PRESET_LOOKUP = new Map(
  VISION_PRESETS.flatMap((preset) =>
    [preset.key, ...(preset.legacyKeys || [])].map((lookupKey) => [lookupKey, preset]),
  ),
);

export function listVisionPresets() {
  return VISION_PRESETS.filter((preset) => !preset.internalOnly).map((preset) => ({
    ...preset,
    legacyKeys: [...(preset.legacyKeys || [])],
    roomCompatibility: [...(preset.roomCompatibility || [])],
    recommendedUse: [...(preset.recommendedUse || [])],
  }));
}

export function resolveVisionPreset(presetKey = 'enhance_listing_quality') {
  return LEGACY_PRESET_LOOKUP.get(presetKey) || LEGACY_PRESET_LOOKUP.get('enhance_listing_quality');
}

export function getVisionPresetKeys() {
  return VISION_PRESETS.flatMap((preset) => [preset.key, ...(preset.legacyKeys || [])]);
}
