const REPLICATE_INPAINT_MODEL =
  'lucataco/sdxl-inpainting:a5b13068cc81a89a4fbeefeccc774869fcb34df4dbc92c1555e0f2771d49dde7';

export const VISION_PRESETS = [
  {
    key: 'enhance_listing_quality',
    legacyKeys: [],
    displayName: 'Enhance for Listing',
    shortLabel: 'Enhanced',
    category: 'enhancement',
    roomCompatibility: ['kitchen', 'living_room', 'bedroom', 'bathroom', 'exterior', 'unknown'],
    providerPreference: 'local_sharp',
    promptVersion: 1,
    outputCount: 1,
    disclaimerType: 'truthful_enhancement',
    recommendedUse: ['brochure', 'report'],
    upgradeTier: 'standard',
    basePrompt:
      'Enhance this real estate photo for listing use. Improve brightness, clarity, and overall presentation while preserving the true structure, layout, and finishes of the room. Keep the image realistic, natural, and honest. Do not invent architectural features or remove major permanent elements.',
    helperText:
      'Improve brightness, clarity, and overall presentation while keeping the room realistic.',
  },
  {
    key: 'declutter_light',
    legacyKeys: ['declutter_preview'],
    displayName: 'Light Declutter',
    shortLabel: 'Declutter',
    category: 'enhancement',
    roomCompatibility: ['kitchen', 'living_room', 'bedroom', 'bathroom', 'unknown'],
    providerPreference: 'replicate',
    promptVersion: 1,
    outputCount: 2,
    disclaimerType: 'truthful_enhancement',
    recommendedUse: ['brochure', 'report'],
    upgradeTier: 'standard',
    basePrompt:
      'Clean up this residential interior photo for real estate listing use. Remove small clutter items from tables, counters, shelves, and floor edges. Improve brightness, neatness, and visual cleanliness. Keep all major furniture, architecture, and layout intact. Stay realistic.',
    helperText:
      'Reduce small distractions and improve presentation while keeping the room believable.',
    strength: 0.6,
    guidanceScale: 7.5,
    numInferenceSteps: 35,
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
  {
    key: 'declutter_medium',
    legacyKeys: [],
    displayName: 'Medium Declutter',
    shortLabel: 'Declutter+',
    category: 'enhancement',
    roomCompatibility: ['kitchen', 'living_room', 'bedroom', 'bathroom', 'unknown'],
    providerPreference: 'replicate',
    promptVersion: 1,
    outputCount: 2,
    disclaimerType: 'truthful_enhancement',
    recommendedUse: ['report'],
    upgradeTier: 'standard',
    basePrompt:
      'Clean and simplify this residential interior photo. Reduce visible clutter and visual noise on surfaces, shelves, side tables, and open floor areas while preserving layout and major furniture. Make the space feel open, tidy, and realistically listing-ready.',
    helperText:
      'A stronger cleanup pass that pushes the room toward listing-readiness without restaging it.',
    strength: 0.75,
    guidanceScale: 7.5,
    numInferenceSteps: 35,
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
  {
    key: 'remove_furniture',
    legacyKeys: [],
    displayName: 'Remove Furniture',
    shortLabel: 'Empty Room',
    category: 'concept_preview',
    roomCompatibility: ['kitchen', 'living_room', 'bedroom', 'bathroom', 'exterior', 'unknown'],
    providerPreference: 'replicate',
    providerStrategy: 'object_removal',
    promptVersion: 6,
    outputCount: 1,
    disclaimerType: 'concept_preview',
    recommendedUse: ['report'],
    upgradeTier: 'standard',
    basePrompt:
      'You are editing a real estate listing photo. Remove ONLY the selected furniture object inside the masked area and reconstruct the newly revealed background realistically. Do NOT restage the room. Do NOT replace, recolor, or reshape furniture. Do NOT change layout, walls, floors, windows, lighting, or room geometry. Preserve perspective, trim lines, and shadows. If the object cannot be removed safely, return the original image unchanged.',
    helperText:
      'Attempt object-level furniture removal for planning previews without silently restaging the room.',
    strength: 0.52,
    guidanceScale: 8.6,
    numInferenceSteps: 40,
    negativePrompt:
      'new furniture, replacement furniture, staged furniture, recolored furniture, reshaped furniture, sofa, couch, chair, coffee table, side table, ottoman, rug, clutter, fireplace, mantel, built-in, new room, different room, low quality, unrealistic geometry, warped lines, distorted walls',
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
  {
    key: 'paint_warm_neutral',
    legacyKeys: [],
    displayName: 'Warm Neutral Walls',
    shortLabel: 'Warm Paint',
    category: 'concept_preview',
    roomCompatibility: ['kitchen', 'living_room', 'bedroom', 'bathroom', 'dining_room', 'office', 'unknown'],
    providerPreference: 'replicate',
    promptVersion: 2,
    outputCount: 2,
    disclaimerType: 'concept_preview',
    recommendedUse: ['report'],
    upgradeTier: 'premium',
    basePrompt:
      'Create a conceptual preview of this room with the walls repainted in a warm neutral tone suitable for broad buyer appeal. Preserve all architecture, trim, windows, built-ins, and layout. Keep the image realistic and suitable for showing a paint concept only.',
    helperText:
      'Preview a buyer-friendly wall repaint without changing the true room structure.',
    strength: 0.8,
    guidanceScale: 8,
    numInferenceSteps: 38,
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
  {
    key: 'paint_bright_white',
    legacyKeys: [],
    displayName: 'Bright White Walls',
    shortLabel: 'White Paint',
    category: 'concept_preview',
    roomCompatibility: ['kitchen', 'living_room', 'bedroom', 'bathroom', 'dining_room', 'office', 'unknown'],
    providerPreference: 'replicate',
    promptVersion: 2,
    outputCount: 2,
    disclaimerType: 'concept_preview',
    recommendedUse: ['report'],
    upgradeTier: 'premium',
    basePrompt:
      'Create a conceptual preview of this room with the walls repainted a bright white tone for a clean and airy listing presentation. Preserve architecture, trim, shadows, and layout. Keep the result realistic and clearly a concept preview.',
    helperText:
      'Show a brighter white-wall concept for a clean, airy feel.',
    strength: 0.8,
    guidanceScale: 8,
    numInferenceSteps: 38,
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
  {
    key: 'paint_soft_greige',
    legacyKeys: [],
    displayName: 'Soft Greige Walls',
    shortLabel: 'Greige Paint',
    category: 'concept_preview',
    roomCompatibility: ['kitchen', 'living_room', 'bedroom', 'bathroom', 'dining_room', 'office', 'unknown'],
    providerPreference: 'replicate',
    promptVersion: 2,
    outputCount: 2,
    disclaimerType: 'concept_preview',
    recommendedUse: ['report'],
    upgradeTier: 'premium',
    basePrompt:
      'Create a conceptual preview of this room with the walls changed to a soft greige tone that feels modern and buyer-friendly. Preserve the room’s true structure, trim, and layout. Keep the output realistic and suitable for listing-planning visualization.',
    helperText:
      'Preview a softer designer-neutral wall palette.',
    strength: 0.8,
    guidanceScale: 8,
    numInferenceSteps: 38,
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
  {
    key: 'floor_light_wood',
    legacyKeys: [],
    displayName: 'Light Wood Floors',
    shortLabel: 'Light Wood',
    category: 'concept_preview',
    roomCompatibility: ['living_room', 'bedroom', 'dining_room', 'office', 'unknown'],
    providerPreference: 'replicate',
    promptVersion: 3,
    outputCount: 3,
    disclaimerType: 'concept_preview',
    recommendedUse: ['report'],
    upgradeTier: 'premium',
    basePrompt:
      'Create a conceptual preview of this room with the flooring changed to a light wood look suitable for a modern residential listing. Preserve room proportions, baseboards, walls, architecture, and flooring perspective lines. Keep the output realistic and clearly a planning concept.',
    helperText:
      'Preview a lighter wood floor finish to modernize the room.',
    strength: 0.9,
    guidanceScale: 9,
    numInferenceSteps: 44,
    negativePrompt:
      'carpet texture, rug pattern, patchy flooring, smeared wood grain, warped floor lines, low quality, unrealistic geometry',
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
  {
    key: 'floor_medium_wood',
    legacyKeys: [],
    displayName: 'Medium Wood Floors',
    shortLabel: 'Medium Wood',
    category: 'concept_preview',
    roomCompatibility: ['living_room', 'bedroom', 'dining_room', 'office', 'unknown'],
    providerPreference: 'replicate',
    promptVersion: 3,
    outputCount: 3,
    disclaimerType: 'concept_preview',
    recommendedUse: ['report'],
    upgradeTier: 'premium',
    basePrompt:
      'Create a conceptual preview of this room with the flooring changed to a medium-tone wood finish that feels warm, modern, and buyer-friendly. Preserve the room structure, layout, baseboards, and perspective. Keep the output realistic and appropriate for planning visualization.',
    helperText:
      'Preview a richer medium-tone wood floor concept.',
    strength: 0.9,
    guidanceScale: 9,
    numInferenceSteps: 44,
    negativePrompt:
      'carpet texture, rug pattern, patchy flooring, smeared wood grain, warped floor lines, low quality, unrealistic geometry',
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
  {
    key: 'floor_dark_hardwood',
    legacyKeys: [],
    displayName: 'Dark Hardwood Floors',
    shortLabel: 'Dark Wood',
    category: 'concept_preview',
    roomCompatibility: ['living_room', 'bedroom', 'dining_room', 'office', 'unknown'],
    providerPreference: 'replicate',
    promptVersion: 3,
    outputCount: 3,
    disclaimerType: 'concept_preview',
    recommendedUse: ['report'],
    upgradeTier: 'premium',
    basePrompt:
      'Create a conceptual preview of this room with the flooring changed to a rich dark hardwood finish that feels upscale and intentional. Preserve room proportions, baseboards, walls, furniture perspective, and architecture. Keep the output realistic and clearly a planning concept.',
    helperText:
      'Preview a richer dark-hardwood floor direction.',
    strength: 0.9,
    guidanceScale: 9,
    numInferenceSteps: 44,
    negativePrompt:
      'carpet texture, rug pattern, patchy flooring, smeared wood grain, warped floor lines, low quality, unrealistic geometry',
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
  {
    key: 'floor_lvp_neutral',
    legacyKeys: [],
    displayName: 'Neutral LVP Floors',
    shortLabel: 'Neutral LVP',
    category: 'concept_preview',
    roomCompatibility: ['living_room', 'bedroom', 'dining_room', 'office', 'kitchen', 'unknown'],
    providerPreference: 'replicate',
    promptVersion: 3,
    outputCount: 3,
    disclaimerType: 'concept_preview',
    recommendedUse: ['report'],
    upgradeTier: 'premium',
    basePrompt:
      'Create a conceptual preview of this room with the flooring changed to a neutral luxury vinyl plank look suitable for a practical, updated residential listing. Preserve architecture, cabinetry, appliances, room proportions, and floor perspective. Keep the image realistic and suitable as a concept only.',
    helperText:
      'Preview a neutral LVP upgrade with a durable, updated feel.',
    strength: 0.9,
    guidanceScale: 9,
    numInferenceSteps: 44,
    negativePrompt:
      'carpet texture, rug pattern, patchy flooring, smeared plank texture, warped floor lines, low quality, unrealistic geometry',
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
  {
    key: 'floor_tile_stone',
    legacyKeys: [],
    displayName: 'Tile / Stone Floors',
    shortLabel: 'Tile / Stone',
    category: 'concept_preview',
    roomCompatibility: ['kitchen', 'bathroom', 'exterior', 'unknown'],
    providerPreference: 'replicate',
    promptVersion: 3,
    outputCount: 3,
    disclaimerType: 'concept_preview',
    recommendedUse: ['report'],
    upgradeTier: 'premium',
    basePrompt:
      'Create a conceptual preview of this room with the flooring changed to a clean tile or stone finish suitable for an updated residential listing. Preserve cabinetry, fixtures, walls, room proportions, grout perspective, and architecture. Keep the output realistic and clearly a concept preview.',
    helperText:
      'Preview a tile or stone floor upgrade for kitchens, baths, or exterior surfaces.',
    strength: 0.9,
    guidanceScale: 9,
    numInferenceSteps: 44,
    negativePrompt:
      'carpet texture, rug pattern, smeared tile lines, warped grout lines, low quality, unrealistic geometry',
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
  {
    key: 'kitchen_white_cabinets_granite',
    legacyKeys: [],
    displayName: 'White Cabinets + Granite',
    shortLabel: 'White Kitchen',
    category: 'concept_preview',
    roomCompatibility: ['kitchen', 'unknown'],
    providerPreference: 'replicate',
    promptVersion: 2,
    outputCount: 2,
    disclaimerType: 'concept_preview',
    recommendedUse: ['report'],
    upgradeTier: 'premium',
    basePrompt:
      'Create a conceptual kitchen upgrade preview with cabinets repainted a crisp white and countertops shown as clean granite. Preserve the real cabinet layout, appliance positions, backsplash alignment, sink, windows, and room geometry. Keep the result realistic and clearly a planning concept.',
    helperText:
      'Preview a brighter kitchen refresh with white cabinetry and granite counters.',
    strength: 0.84,
    guidanceScale: 8,
    numInferenceSteps: 40,
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
  {
    key: 'kitchen_white_cabinets_quartz',
    legacyKeys: [],
    displayName: 'White Cabinets + Quartz',
    shortLabel: 'White + Quartz',
    category: 'concept_preview',
    roomCompatibility: ['kitchen', 'unknown'],
    providerPreference: 'replicate',
    promptVersion: 2,
    outputCount: 2,
    disclaimerType: 'concept_preview',
    recommendedUse: ['report'],
    upgradeTier: 'premium',
    basePrompt:
      'Create a conceptual kitchen upgrade preview with cabinets repainted a crisp white and countertops shown as clean quartz. Preserve the real cabinet layout, appliance positions, backsplash alignment, sink, windows, and room geometry. Keep the result realistic and clearly a planning concept.',
    helperText:
      'Preview a brighter kitchen refresh with white cabinetry and quartz counters.',
    strength: 0.84,
    guidanceScale: 8,
    numInferenceSteps: 40,
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
  {
    key: 'kitchen_green_cabinets_granite',
    legacyKeys: [],
    displayName: 'Green Cabinets + Granite',
    shortLabel: 'Green Kitchen',
    category: 'concept_preview',
    roomCompatibility: ['kitchen', 'unknown'],
    providerPreference: 'replicate',
    promptVersion: 2,
    outputCount: 2,
    disclaimerType: 'concept_preview',
    recommendedUse: ['report'],
    upgradeTier: 'premium',
    basePrompt:
      'Create a conceptual kitchen upgrade preview with cabinets repainted a refined sage or deep green tone and countertops shown as elegant granite. Preserve cabinet alignment, countertop edges, appliances, backsplash, sink, windows, and true room geometry. Keep the result realistic and clearly a planning concept.',
    helperText:
      'Preview a designer kitchen update with green cabinetry and granite counters.',
    strength: 0.84,
    guidanceScale: 8,
    numInferenceSteps: 40,
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
  {
    key: 'kitchen_green_cabinets_quartz',
    legacyKeys: [],
    displayName: 'Green Cabinets + Quartz',
    shortLabel: 'Green + Quartz',
    category: 'concept_preview',
    roomCompatibility: ['kitchen', 'unknown'],
    providerPreference: 'replicate',
    promptVersion: 2,
    outputCount: 2,
    disclaimerType: 'concept_preview',
    recommendedUse: ['report'],
    upgradeTier: 'premium',
    basePrompt:
      'Create a conceptual kitchen upgrade preview with cabinets repainted a refined sage or deep green tone and countertops shown as elegant quartz. Preserve cabinet alignment, countertop edges, appliances, backsplash, sink, windows, and true room geometry. Keep the result realistic and clearly a planning concept.',
    helperText:
      'Preview a designer kitchen update with green cabinetry and quartz counters.',
    strength: 0.84,
    guidanceScale: 8,
    numInferenceSteps: 40,
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
  {
    key: 'exterior_curb_appeal_refresh',
    legacyKeys: [],
    displayName: 'Curb Appeal Refresh',
    shortLabel: 'Curb Appeal',
    category: 'concept_preview',
    roomCompatibility: ['exterior', 'unknown'],
    providerPreference: 'replicate',
    promptVersion: 2,
    outputCount: 2,
    disclaimerType: 'concept_preview',
    recommendedUse: ['report'],
    upgradeTier: 'premium',
    basePrompt:
      'Create a conceptual curb-appeal upgrade preview for this exterior photo with refreshed landscaping, cleaner planting beds, improved pathway lighting or fixtures, and stronger first-impression presentation. Preserve the home structure, roofline, windows, doors, driveway, and lot boundaries. Keep the result realistic and clearly a planning concept.',
    helperText:
      'Preview stronger front-exterior landscaping and fixture upgrades.',
    strength: 0.82,
    guidanceScale: 8,
    numInferenceSteps: 40,
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
  {
    key: 'backyard_entertaining_refresh',
    legacyKeys: [],
    displayName: 'Backyard Entertaining Refresh',
    shortLabel: 'Backyard Refresh',
    category: 'concept_preview',
    roomCompatibility: ['exterior', 'unknown'],
    providerPreference: 'replicate',
    promptVersion: 2,
    outputCount: 2,
    disclaimerType: 'concept_preview',
    recommendedUse: ['report'],
    upgradeTier: 'premium',
    basePrompt:
      'Create a conceptual backyard upgrade preview with more intentional plants, cleaner hardscape, refreshed fixtures or lighting, and a more inviting entertaining feel. Preserve fences, lot boundaries, house structure, patio geometry, and true exterior layout. Keep the result realistic and suitable for planning visualization.',
    helperText:
      'Preview a more polished backyard with plants, fixtures, and entertaining appeal.',
    strength: 0.82,
    guidanceScale: 8,
    numInferenceSteps: 40,
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
  {
    key: 'backyard_pool_preview',
    legacyKeys: [],
    displayName: 'Pool / Water Feature Preview',
    shortLabel: 'Pool Concept',
    category: 'concept_preview',
    roomCompatibility: ['exterior', 'unknown'],
    providerPreference: 'replicate',
    promptVersion: 2,
    outputCount: 2,
    disclaimerType: 'concept_preview',
    recommendedUse: ['report'],
    upgradeTier: 'premium',
    basePrompt:
      'Create a conceptual backyard planning preview that adds a tasteful pool or water-feature concept while preserving the home, yard boundaries, patio geometry, and overall lot shape. Keep the water feature proportional, realistic, and clearly suitable for budget-planning discussion rather than representing an existing improvement.',
    helperText:
      'Preview a future pool or water-feature concept for the backyard.',
    strength: 0.84,
    guidanceScale: 8,
    numInferenceSteps: 40,
    replicateModel: REPLICATE_INPAINT_MODEL,
  },
  {
    key: 'combined_listing_refresh',
    legacyKeys: [],
    displayName: 'Listing Refresh',
    shortLabel: 'Refresh',
    category: 'enhancement',
    roomCompatibility: ['kitchen', 'living_room', 'bedroom', 'bathroom', 'exterior', 'unknown'],
    providerPreference: 'local_sharp',
    promptVersion: 1,
    outputCount: 1,
    disclaimerType: 'truthful_enhancement',
    recommendedUse: ['brochure', 'report'],
    upgradeTier: 'standard',
    basePrompt:
      'Transform this room photo into a cleaner, brighter, more listing-ready version. Improve lighting, reduce clutter, and create a polished real-estate-photo feel while preserving the room’s true structure, layout, and finishes. Keep the image realistic and honest.',
    helperText:
      'Blend enhancement and cleanup into a more polished listing-ready image.',
  },
];

const LEGACY_PRESET_LOOKUP = new Map(
  VISION_PRESETS.flatMap((preset) =>
    [preset.key, ...(preset.legacyKeys || [])].map((lookupKey) => [lookupKey, preset]),
  ),
);

export function listVisionPresets() {
  return VISION_PRESETS.map((preset) => ({
    ...preset,
    legacyKeys: [...(preset.legacyKeys || [])],
    roomCompatibility: [...(preset.roomCompatibility || [])],
    recommendedUse: [...(preset.recommendedUse || [])],
  }));
}

export function resolveVisionPreset(presetKey = 'enhance_listing_quality') {
  return LEGACY_PRESET_LOOKUP.get(presetKey) || LEGACY_PRESET_LOOKUP.get('enhance_listing_quality');
}

export function getVisionPresetKeys() {
  return VISION_PRESETS.flatMap((preset) => [preset.key, ...(preset.legacyKeys || [])]);
}
